apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
data:
  application.yml: |
    micronaut:
      server:
        port: {{ .Values.deployment.containerPort }}
      application:
        name: sayHelloMicronaut
    sayhello:
      greeting: {{ .Values.deployment.welcomeMessage }}   
  elasticapm.properties: |
    service_name={{ .Values.name }}
    application_packages={{ .Values.elastic.apm.applicationPackages }}
    environment={{ .Values.elastic.apm.environment }}
    log_level={{ .Values.elastic.apm.logLevel }}
    secret_token={{ .Values.elastic.apm.secretToken }}
    server_url={{ .Values.elastic.apm.serverUrl }}
  logback.xml: |
    <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <withJansi>true</withJansi>
            <!-- encoders are assigned the type
                 ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
            <encoder>
                <pattern>%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n</pattern>
            </encoder>
        </appender>

        <root level="{{ .Values.log.level }}">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>


